// Keeps the action reference in step with the app.
//
//   node scripts/actions.ts               sync src/data/actions.json from the app checkout, then check
//   node scripts/actions.ts --from FILE   sync from a contract file (the actions.json of a Lunchpad release), then check
//   node scripts/actions.ts --check       only check (no Lunchpad checkout needed)
//
// The data itself is the app's action contract, generated by the app
// (tools/actions-contract.ts there): the action list, the "Add action" menu,
// icon names and drawings, the English names, and the JSON each action is,
// read from the Rust model. Every Lunchpad release attaches it as actions.json
// and the "Sync with Lunchpad" workflow of this repository opens a pull request
// with it; locally the sync runs the app's tool on the checkout next door
// (../../lunchpad, or LUNCHPAD_DIR). The check fails when an action the app
// ships has no docs page or no screenshot.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const DOCS = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const LUNCHPAD = resolve(process.env.LUNCHPAD_DIR ?? join(DOCS, "../../lunchpad"));
const DATA = join(DOCS, "src/data/actions.json");
const PAGES = join(DOCS, "src/content/docs/actions");
const SHOTS = join(DOCS, "src/assets/screenshots/actions");

interface ActionInfo {
  name: string;
  desc: string;
  group: string;
  icon: string;
  /** false for the markers that come with a menu entry (Otherwise, End condition, …) */
  menu: boolean;
  /** the action row has a Wait switch */
  wait: boolean;
  /** the menu entry a marker belongs to */
  partOf?: string;
}

/** The app's action contract, as `tools/actions-contract.ts` writes it. */
interface ActionData {
  /** The Lunchpad version it describes. */
  app?: string;
  groups: { id: string; name: string; icon: string; types: string[] }[];
  actions: Record<string, ActionInfo>;
  icons: Record<string, { viewBox: string; body: string }>;
  payloads: Record<string, unknown>;
  types: Record<string, unknown>;
}

function asContract(json: string, source: string): ActionData {
  const data = JSON.parse(json) as Partial<ActionData>;
  for (const key of ["groups", "actions", "icons", "payloads", "types"] as const) {
    if (!data[key] || typeof data[key] !== "object") throw new Error(`${source} is not an action contract: no "${key}" in it`);
  }
  return data as ActionData;
}

/** The contract generated from the app checkout next door. */
function fromCheckout(): ActionData {
  const tool = join(LUNCHPAD, "tools/actions-contract.ts");
  if (!existsSync(tool)) {
    throw new Error(`${tool} is missing: the checkout at ${LUNCHPAD} is older than Lunchpad 1.1.1, which introduced the action contract. Update it, or sync from a release with --from actions.json.`);
  }
  const json = execFileSync(process.execPath, [tool], { cwd: LUNCHPAD, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
  return asContract(json, tool);
}

function sync(data: ActionData, source: string): ActionData {
  writeFileSync(DATA, JSON.stringify(data, null, 2) + "\n");
  console.log(`synced ${Object.keys(data.actions).length} actions of Lunchpad ${data.app ?? "?"} from ${source}, with ${Object.keys(data.payloads).length} payloads and ${Object.keys(data.types).length} types`);
  return data;
}

/** Action types a docs page claims in its `actionTypes` frontmatter. */
function documentedTypes(): Map<string, string> {
  const found = new Map<string, string>();
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) walk(path);
      else if (/\.mdx?$/.test(entry.name)) {
        const front = /^---\n([\s\S]*?)\n---/.exec(readFileSync(path, "utf8"))?.[1] ?? "";
        const list = /actionTypes:\s*\[([^\]]*)\]/.exec(front)?.[1] ?? "";
        list.split(",").map((s) => s.trim().replace(/["']/g, "")).filter(Boolean).forEach((t) => found.set(t, relative(DOCS, path)));
      }
    }
  };
  if (existsSync(PAGES)) walk(PAGES);
  return found;
}

function check(data: ActionData): boolean {
  const pages = documentedTypes();
  const problems: string[] = [];
  for (const [type, info] of Object.entries(data.actions)) {
    if (!pages.has(type)) problems.push(`${type} (${info.name}): no page lists it in actionTypes`);
    if (info.menu && !existsSync(join(SHOTS, `${type}.png`))) problems.push(`${type} (${info.name}): no screenshot src/assets/screenshots/actions/${type}.png`);
  }
  for (const [type, page] of pages) if (!data.actions[type]) problems.push(`${page} documents "${type}", which the app does not have (renamed or removed?)`);
  if (problems.length) {
    console.error(`Action docs are out of date:\n  - ${problems.join("\n  - ")}\nSee CONTRIBUTING.md → "When a new action ships".`);
    return false;
  }
  console.log(`all ${Object.keys(data.actions).length} actions are documented, with screenshots`);
  return true;
}

const args = process.argv.slice(2);
const from = args.indexOf("--from");
let data: ActionData;
if (from >= 0) data = sync(asContract(readFileSync(args[from + 1], "utf8"), args[from + 1]), args[from + 1]);
else if (args.includes("--check") || !existsSync(LUNCHPAD)) data = asContract(readFileSync(DATA, "utf8"), DATA);
else data = sync(fromCheckout(), LUNCHPAD);
process.exit(check(data) ? 0 : 1);
